/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LocationRouteImport } from './routes/location'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as IndexRouteImport } from './routes/index'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/reviews'
    | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/reviews'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/reviews'
    | '/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LocationRoute: typeof LocationRoute
  ReviewsRoute: typeof ReviewsRoute
  RoomsRoute: typeof RoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmenitiesRoute: AmenitiesRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LocationRoute: LocationRoute,
  ReviewsRoute: ReviewsRoute,
  RoomsRoute: RoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
